# Generated by Django 6.0.1 on 2026-01-13 04:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("resume_builder", "0007_add_photo_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="JobPosting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, max_length=220, unique=True)),
                ("department", models.CharField(max_length=100)),
                ("location", models.CharField(max_length=100)),
                (
                    "location_type",
                    models.CharField(
                        choices=[
                            ("remote", "Remote"),
                            ("onsite", "On-site"),
                            ("hybrid", "Hybrid"),
                        ],
                        default="remote",
                        max_length=20,
                    ),
                ),
                (
                    "employment_type",
                    models.CharField(
                        choices=[
                            ("full_time", "Full-time"),
                            ("part_time", "Part-time"),
                            ("contract", "Contract"),
                            ("internship", "Internship"),
                        ],
                        default="full_time",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(help_text="Full job description")),
                (
                    "responsibilities",
                    models.TextField(help_text="One responsibility per line"),
                ),
                (
                    "requirements",
                    models.TextField(help_text="One requirement per line"),
                ),
                (
                    "tech_stack",
                    models.JSONField(
                        blank=True, default=list, help_text="List of technologies"
                    ),
                ),
                ("salary_range", models.CharField(blank=True, max_length=100)),
                ("is_active", models.BooleanField(default=True)),
                ("closes_at", models.DateTimeField(blank=True, null=True)),
                ("view_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Job Posting",
                "verbose_name_plural": "Job Postings",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("applicant_name", models.CharField(max_length=200)),
                ("applicant_email", models.EmailField(max_length=254)),
                ("portfolio_url", models.URLField(blank=True)),
                ("linkedin_url", models.URLField(blank=True)),
                ("github_url", models.URLField(blank=True)),
                ("additional_notes", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("applied", "Applied"),
                            ("under_review", "Under Review"),
                            ("interview", "Interview"),
                            ("rejected", "Rejected"),
                            ("hired", "Hired"),
                        ],
                        default="applied",
                        max_length=20,
                    ),
                ),
                ("applied_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cover_letter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="job_applications",
                        to="resume_builder.coverletter",
                    ),
                ),
                (
                    "resume",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="job_applications",
                        to="resume_builder.resume",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_applications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to="careers.jobposting",
                    ),
                ),
            ],
            options={
                "verbose_name": "Application",
                "verbose_name_plural": "Applications",
                "ordering": ["-applied_at"],
                "unique_together": {("job", "user")},
            },
        ),
        migrations.CreateModel(
            name="ApplicationNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to="careers.application",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="application_notes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Application Note",
                "verbose_name_plural": "Application Notes",
                "ordering": ["-created_at"],
            },
        ),
    ]
