# Generated by Django 6.0.1 on 2026-01-13 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("careers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobposting",
            name="benefits",
            field=models.TextField(
                blank=True, help_text="What we offer, one benefit per line"
            ),
        ),
        migrations.AddField(
            model_name="jobposting",
            name="experience_range",
            field=models.CharField(
                blank=True, help_text="e.g., 3-5 years", max_length=50
            ),
        ),
        migrations.AddField(
            model_name="jobposting",
            name="nice_to_have",
            field=models.TextField(
                blank=True, help_text="Optional skills, one per line"
            ),
        ),
    ]
