# Generated by Django 6.0.1 on 2026-01-13 05:19

import careers.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("careers", "0002_add_nice_to_have_benefits_experience"),
        ("resume_builder", "0007_add_photo_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="uploaded_cover_letter",
            field=models.FileField(
                blank=True,
                help_text="Upload cover letter as PDF (max 5MB)",
                null=True,
                upload_to=careers.models.application_cover_letter_path,
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="uploaded_cover_letter_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="application",
            name="uploaded_resume",
            field=models.FileField(
                blank=True,
                help_text="Upload resume as PDF (max 5MB)",
                null=True,
                upload_to=careers.models.application_resume_path,
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="uploaded_resume_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="application",
            name="resume",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="job_applications",
                to="resume_builder.resume",
            ),
        ),
    ]
