# Generated by Django 6.0.1 on 2026-01-11 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("roadmap", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="JourneySkill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "icon_class",
                    models.CharField(
                        default="fas fa-code",
                        help_text="Font Awesome icon class (e.g., fab fa-aws, fab fa-docker)",
                        max_length=100,
                    ),
                ),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "roadmap_path",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="journey_skills",
                        to="roadmap.roadmappath",
                    ),
                ),
            ],
            options={
                "verbose_name": "Journey Skill",
                "verbose_name_plural": "Journey Skills",
                "ordering": ["roadmap_path", "display_order"],
            },
        ),
    ]
