# Generated by Django 6.0.1 on 2026-01-11 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("roadmap", "0004_add_journey_skill_progress"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="journeyskill",
            options={
                "ordering": ["roadmap_path", "display_order"],
                "verbose_name": "Journey Tool",
                "verbose_name_plural": "Journey Tools",
            },
        ),
        migrations.AddField(
            model_name="journeyskill",
            name="external_url",
            field=models.URLField(
                blank=True,
                help_text="External URL to official documentation or learning resource",
                max_length=500,
            ),
        ),
        migrations.DeleteModel(
            name="JourneySkillProgress",
        ),
    ]
