# Generated by Copilot script
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_review'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Movie',
            new_name='Book',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='movie',
            new_name='book',
        ),
        # rename image -> cover_image for the renamed model
        migrations.RenameField(
            model_name='book',
            old_name='image',
            new_name='cover_image',
        ),
        migrations.AddField(
            model_name='book',
            name='pdf',
            field=models.FileField(upload_to='book_pdfs/', null=True, blank=True),
        ),
    ]
