# Generated by Django 6.0 on 2026-01-06 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0005_category_book_category"),
    ]

    def create_initial_categories(apps, schema_editor):
        Category = apps.get_model('movies', 'Category')
        Book = apps.get_model('movies', 'Book')
        categories = [
            ('JavaScript', 'javascript'),
            ('Windows', 'windows'),
            ('Elasticsearch', 'elasticsearch'),
            ('Nginx', 'nginx'),
            ('Node.js', 'node-js'),
            ('TypeScript', 'typescript'),
            ('Kubernetes', 'kubernetes'),
        ]
        for name, slug in categories:
            Category.objects.get_or_create(name=name, slug=slug)

        # Assign books to categories where the pdf path contains the category slug
        for b in Book.objects.all():
            if b.pdf and isinstance(b.pdf.name, str):
                for name, slug in categories:
                    if slug in b.pdf.name:
                        b.category = Category.objects.filter(slug=slug).first()
                        b.save()
                        break

    operations = [
        migrations.RunPython(create_initial_categories, reverse_code=migrations.RunPython.noop),
    ]
