# Generated by Django 5.0.6 on 2026-01-11 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resume_builder", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="resume",
            name="certifications",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="resume",
            name="github",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="resume",
            name="languages",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="resume",
            name="projects",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="resume",
            name="role",
            field=models.CharField(
                choices=[
                    ("devops_sre", "DevOps / SRE Engineer"),
                    ("software_engineer", "Software Engineer"),
                    ("ds_ml", "DS / ML Engineer"),
                ],
                default="software_engineer",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="resume",
            name="role_title",
            field=models.CharField(
                blank=True, help_text="e.g., Senior DevOps Engineer", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="resume",
            name="skills",
            field=models.JSONField(default=dict),
        ),
    ]
