# Generated by Django 5.0.6 on 2026-01-11 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resume_builder", "0002_add_role_based_resume_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="resume",
            name="address",
            field=models.TextField(blank=True, help_text="Full address"),
        ),
        migrations.AddField(
            model_name="resume",
            name="primary_color",
            field=models.CharField(
                default="#4a9d9a", help_text="Header/accent color", max_length=7
            ),
        ),
        migrations.AddField(
            model_name="resume",
            name="profile_photo",
            field=models.ImageField(blank=True, null=True, upload_to="resume_photos/"),
        ),
        migrations.AddField(
            model_name="resumetemplate",
            name="primary_color",
            field=models.CharField(
                default="#4a9d9a", help_text="Primary color hex code", max_length=7
            ),
        ),
        migrations.AlterField(
            model_name="resume",
            name="skills",
            field=models.JSONField(default=list),
        ),
    ]
