# Generated by Django 5.0.6 on 2026-01-11 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resume_builder", "0003_add_profile_photo_and_color"),
    ]

    operations = [
        migrations.AddField(
            model_name="coverletter",
            name="address",
            field=models.TextField(blank=True, help_text="Full address"),
        ),
        migrations.AddField(
            model_name="coverletter",
            name="body_paragraph",
            field=models.TextField(
                blank=True, help_text="Your qualifications and achievements"
            ),
        ),
        migrations.AddField(
            model_name="coverletter",
            name="closing_paragraph",
            field=models.TextField(blank=True, help_text="Call to action and closing"),
        ),
        migrations.AddField(
            model_name="coverletter",
            name="company_address",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="coverletter",
            name="linkedin",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="coverletter",
            name="opening_paragraph",
            field=models.TextField(
                blank=True, help_text="Introduction and why you're applying"
            ),
        ),
        migrations.AddField(
            model_name="coverletter",
            name="primary_color",
            field=models.CharField(
                default="#4a9d9a", help_text="Header/accent color", max_length=7
            ),
        ),
        migrations.AddField(
            model_name="coverlettertemplate",
            name="primary_color",
            field=models.CharField(
                default="#4a9d9a", help_text="Primary color hex code", max_length=7
            ),
        ),
        migrations.AlterField(
            model_name="coverletter",
            name="content",
            field=models.TextField(blank=True),
        ),
    ]
