# Generated by Django 6.0.1 on 2026-01-11 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resume_builder", "0004_add_cover_letter_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="resumetemplate",
            name="preview_image",
            field=models.ImageField(
                blank=True,
                help_text="High-quality preview image of the template (recommended: 850x1100px)",
                null=True,
                upload_to="template_previews/",
            ),
        ),
    ]
