# Generated by Django 6.0.1 on 2026-01-12 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resume_builder", "0006_add_cover_letter_templates"),
    ]

    operations = [
        migrations.AddField(
            model_name="resume",
            name="photo_position",
            field=models.CharField(
                default="top", help_text="top, center, or bottom", max_length=20
            ),
        ),
        migrations.AddField(
            model_name="resume",
            name="photo_shape",
            field=models.CharField(
                default="circle", help_text="circle, rounded, or square", max_length=20
            ),
        ),
        migrations.AddField(
            model_name="resume",
            name="photo_size",
            field=models.CharField(
                default="medium", help_text="small, medium, or large", max_length=20
            ),
        ),
    ]
