# Generated by Django 6.0.1 on 2026-01-13 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resume_builder", "0007_add_photo_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="coverlettertemplate",
            options={"ordering": ["display_order", "tone", "name"]},
        ),
        migrations.AlterModelOptions(
            name="resumetemplate",
            options={"ordering": ["display_order", "category", "name"]},
        ),
        migrations.AddField(
            model_name="coverlettertemplate",
            name="display_order",
            field=models.IntegerField(
                default=0, help_text="Order in template selector (lower = first)"
            ),
        ),
        migrations.AddField(
            model_name="coverlettertemplate",
            name="paired_resume_template",
            field=models.ForeignKey(
                blank=True,
                help_text="Recommended resume template to pair with this cover letter",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="paired_cover_letters",
                to="resume_builder.resumetemplate",
            ),
        ),
        migrations.AddField(
            model_name="coverlettertemplate",
            name="preview_image",
            field=models.ImageField(
                blank=True,
                help_text="High-quality preview image of the template (recommended: 850x1100px)",
                null=True,
                upload_to="cl_template_previews/",
            ),
        ),
        migrations.AddField(
            model_name="resumetemplate",
            name="display_order",
            field=models.IntegerField(
                default=0, help_text="Order in template selector (lower = first)"
            ),
        ),
        migrations.AddField(
            model_name="resumetemplate",
            name="is_ats_safe",
            field=models.BooleanField(
                default=True, help_text="Whether template is ATS-compatible"
            ),
        ),
        migrations.AddField(
            model_name="resumetemplate",
            name="recommended_roles",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='List of role slugs this template is recommended for (e.g., ["software_engineer", "devops_sre"])',
            ),
        ),
        migrations.AlterField(
            model_name="coverlettertemplate",
            name="tone",
            field=models.CharField(
                choices=[
                    ("formal", "Formal"),
                    ("professional", "Professional"),
                    ("modern", "Modern"),
                    ("creative", "Creative"),
                ],
                default="professional",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="resumetemplate",
            name="category",
            field=models.CharField(
                choices=[
                    ("professional", "Professional"),
                    ("modern", "Modern"),
                    ("executive", "Executive"),
                    ("minimal", "Minimal"),
                    ("creative", "Creative"),
                ],
                default="professional",
                max_length=20,
            ),
        ),
    ]
