# Generated by Django 6.0.1 on 2026-01-13 14:18

from django.db import migrations


def add_minimal_template(apps, schema_editor):
    """Add the Minimal Clean resume template."""
    ResumeTemplate = apps.get_model('resume_builder', 'ResumeTemplate')
    
    # Check if template already exists
    if not ResumeTemplate.objects.filter(slug='minimal').exists():
        ResumeTemplate.objects.create(
            name='Minimal Clean',
            slug='minimal',
            category='minimal',
            description='Clean single-column layout with maximum whitespace and subtle accents. Perfect for creative and design roles.',
            html_template='',  # Not used - rendering is in pdf_generator.py
            css_styles='',     # Not used - rendering is in pdf_generator.py
            primary_color='#374151',  # Graphite gray
            is_active=True,
            is_ats_safe=True,
            recommended_roles=['software_engineer', 'ds_ml'],
            display_order=4,
        )


def remove_minimal_template(apps, schema_editor):
    """Remove the Minimal Clean template."""
    ResumeTemplate = apps.get_model('resume_builder', 'ResumeTemplate')
    ResumeTemplate.objects.filter(slug='minimal').delete()


class Migration(migrations.Migration):

    dependencies = [
        ("resume_builder", "0008_template_system_redesign"),
    ]

    operations = [
        migrations.RunPython(add_minimal_template, remove_minimal_template),
    ]
