# Generated by Django 5.0.6 on 2026-01-13 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resume_builder", "0016_add_3_more_cover_letter_templates"),
    ]

    operations = [
        migrations.AddField(
            model_name="coverletter",
            name="target_role",
            field=models.CharField(
                choices=[
                    ("devops_sre", "DevOps / SRE Engineer"),
                    ("software_engineer", "Software Engineer"),
                    ("ds_ml", "DS / ML Engineer"),
                ],
                default="software_engineer",
                help_text="Target role for AI content suggestions",
                max_length=30,
            ),
        ),
    ]
