# Generated by Django 5.0.6 on 2026-01-13 19:58

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ApprovalWorkflow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "request_type",
                    models.CharField(
                        choices=[
                            ("leave", "Leave Request"),
                            ("expense", "Expense Request"),
                            ("timesheet", "Timesheet"),
                            ("asset", "Asset Request"),
                        ],
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("requires_manager_approval", models.BooleanField(default=True)),
                ("requires_hr_approval", models.BooleanField(default=True)),
                ("requires_finance_approval", models.BooleanField(default=False)),
                (
                    "auto_approve_threshold",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Auto-approve if amount/days below this threshold",
                        max_digits=10,
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Approval Workflow",
                "verbose_name_plural": "Approval Workflows",
            },
        ),
        migrations.CreateModel(
            name="AssetCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("code", models.CharField(max_length=10, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "depreciation_years",
                    models.PositiveIntegerField(
                        default=3, help_text="Years for depreciation"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Asset Category",
                "verbose_name_plural": "Asset Categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ExpenseCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("code", models.CharField(max_length=10, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "max_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Maximum claimable amount per request",
                        max_digits=10,
                        null=True,
                    ),
                ),
                ("requires_receipt", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Expense Category",
                "verbose_name_plural": "Expense Categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="LeaveType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("code", models.CharField(max_length=10, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "default_days",
                    models.PositiveIntegerField(
                        default=0, help_text="Default annual allocation"
                    ),
                ),
                ("is_paid", models.BooleanField(default=True)),
                (
                    "is_carry_forward",
                    models.BooleanField(
                        default=False, help_text="Can unused days be carried forward?"
                    ),
                ),
                ("max_carry_forward_days", models.PositiveIntegerField(default=0)),
                ("requires_approval", models.BooleanField(default=True)),
                (
                    "requires_document",
                    models.BooleanField(
                        default=False, help_text="Requires supporting document?"
                    ),
                ),
                (
                    "min_days_notice",
                    models.PositiveIntegerField(
                        default=0, help_text="Minimum days notice required"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "color",
                    models.CharField(
                        default="#3B82F6",
                        help_text="Color for calendar display",
                        max_length=7,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Leave Type",
                "verbose_name_plural": "Leave Types",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("asset_id", models.CharField(max_length=30, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("serial_number", models.CharField(blank=True, max_length=100)),
                ("model", models.CharField(blank=True, max_length=100)),
                ("manufacturer", models.CharField(blank=True, max_length=100)),
                (
                    "specifications",
                    models.JSONField(
                        blank=True, default=dict, help_text="Additional specs as JSON"
                    ),
                ),
                ("purchase_date", models.DateField(blank=True, null=True)),
                (
                    "purchase_cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("warranty_expiry", models.DateField(blank=True, null=True)),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("good", "Good"),
                            ("fair", "Fair"),
                            ("poor", "Poor"),
                            ("damaged", "Damaged"),
                            ("disposed", "Disposed"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("assigned", "Assigned"),
                            ("maintenance", "Under Maintenance"),
                            ("retired", "Retired"),
                        ],
                        default="available",
                        max_length=20,
                    ),
                ),
                ("location", models.CharField(blank=True, max_length=100)),
                ("assigned_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assets",
                        to="hr_portal.assetcategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Asset",
                "verbose_name_plural": "Assets",
                "ordering": ["asset_id"],
                "permissions": [
                    ("manage_assets", "Can manage company assets"),
                    ("assign_assets", "Can assign assets to employees"),
                    ("view_all_assets", "Can view all assets"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("code", models.CharField(max_length=20, unique=True)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sub_departments",
                        to="hr_portal.department",
                    ),
                ),
            ],
            options={
                "verbose_name": "Department",
                "verbose_name_plural": "Departments",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Designation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                (
                    "level",
                    models.PositiveIntegerField(
                        default=1, help_text="Hierarchy level (1=Entry, 10=Executive)"
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="designations",
                        to="hr_portal.department",
                    ),
                ),
            ],
            options={
                "ordering": ["department", "level", "title"],
                "unique_together": {("title", "department")},
            },
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "employee_id",
                    models.CharField(
                        help_text="Unique employee identifier (e.g., EMP001)",
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("other", "Other"),
                            ("prefer_not_to_say", "Prefer not to say"),
                        ],
                        max_length=20,
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("personal_email", models.EmailField(blank=True, max_length=254)),
                ("address", models.TextField(blank=True)),
                (
                    "emergency_contact_name",
                    models.CharField(blank=True, max_length=100),
                ),
                (
                    "emergency_contact_phone",
                    models.CharField(blank=True, max_length=20),
                ),
                (
                    "employment_type",
                    models.CharField(
                        choices=[
                            ("full_time", "Full Time"),
                            ("part_time", "Part Time"),
                            ("contract", "Contract"),
                            ("intern", "Intern"),
                            ("consultant", "Consultant"),
                        ],
                        default="full_time",
                        max_length=20,
                    ),
                ),
                (
                    "employment_status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("on_leave", "On Leave"),
                            ("notice_period", "Notice Period"),
                            ("terminated", "Terminated"),
                            ("resigned", "Resigned"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("joining_date", models.DateField()),
                ("confirmation_date", models.DateField(blank=True, null=True)),
                ("termination_date", models.DateField(blank=True, null=True)),
                (
                    "work_location",
                    models.CharField(
                        blank=True,
                        help_text="Office location or Remote",
                        max_length=100,
                    ),
                ),
                (
                    "profile_photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="hr_portal/employee_photos/"
                    ),
                ),
                (
                    "bio",
                    models.TextField(blank=True, help_text="Short professional bio"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_employees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="employees",
                        to="hr_portal.department",
                    ),
                ),
                (
                    "designation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="employees",
                        to="hr_portal.designation",
                    ),
                ),
                (
                    "reporting_manager",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="direct_reports",
                        to="hr_portal.employee",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employee_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Employee",
                "verbose_name_plural": "Employees",
                "ordering": ["employee_id"],
                "permissions": [
                    ("view_all_employees", "Can view all employees"),
                    ("manage_employees", "Can manage employee records"),
                    ("view_team_employees", "Can view team employees"),
                ],
            },
        ),
        migrations.AddField(
            model_name="department",
            name="head",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="headed_departments",
                to="hr_portal.employee",
            ),
        ),
        migrations.CreateModel(
            name="AssetAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "assignment_type",
                    models.CharField(
                        choices=[
                            ("assigned", "Assigned"),
                            ("transferred", "Transferred"),
                            ("temporary", "Temporary"),
                        ],
                        default="assigned",
                        max_length=20,
                    ),
                ),
                ("assigned_date", models.DateField(auto_now_add=True)),
                ("returned_date", models.DateField(blank=True, null=True)),
                ("return_condition", models.CharField(blank=True, max_length=20)),
                ("return_notes", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="hr_portal.asset",
                    ),
                ),
                (
                    "assigned_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assets_assigned_by",
                        to="hr_portal.employee",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="asset_assignments",
                        to="hr_portal.employee",
                    ),
                ),
            ],
            options={
                "verbose_name": "Asset Assignment",
                "verbose_name_plural": "Asset Assignments",
                "ordering": ["-assigned_date"],
            },
        ),
        migrations.AddField(
            model_name="asset",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_assets",
                to="hr_portal.employee",
            ),
        ),
        migrations.CreateModel(
            name="HRRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role_type",
                    models.CharField(
                        choices=[
                            ("app_admin", "App Admin"),
                            ("hr_admin", "HR Admin"),
                            ("finance_admin", "Finance Admin"),
                            ("manager", "Manager"),
                            ("employee", "Employee"),
                        ],
                        default="employee",
                        max_length=20,
                    ),
                ),
                (
                    "is_employee",
                    models.BooleanField(
                        default=False, help_text="User is marked as an employee"
                    ),
                ),
                ("can_access_hr_portal", models.BooleanField(default=False)),
                ("can_manage_employees", models.BooleanField(default=False)),
                ("can_manage_leaves", models.BooleanField(default=False)),
                ("can_manage_expenses", models.BooleanField(default=False)),
                ("can_manage_assets", models.BooleanField(default=False)),
                ("can_manage_timesheets", models.BooleanField(default=False)),
                ("can_manage_projects", models.BooleanField(default=False)),
                ("can_manage_holidays", models.BooleanField(default=False)),
                ("can_view_reports", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_hr_roles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hr_role",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "HR Role",
                "verbose_name_plural": "HR Roles",
            },
        ),
        migrations.CreateModel(
            name="LeaveRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "request_id",
                    models.CharField(editable=False, max_length=20, unique=True),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "duration_type",
                    models.CharField(
                        choices=[
                            ("full_day", "Full Day"),
                            ("first_half", "First Half"),
                            ("second_half", "Second Half"),
                        ],
                        default="full_day",
                        max_length=20,
                    ),
                ),
                ("total_days", models.DecimalField(decimal_places=1, max_digits=5)),
                ("reason", models.TextField()),
                (
                    "supporting_document",
                    models.FileField(
                        blank=True, null=True, upload_to="hr_portal/leave_documents/"
                    ),
                ),
                ("contact_during_leave", models.CharField(blank=True, max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending", "Pending Approval"),
                            ("manager_approved", "Manager Approved"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("manager_approved_at", models.DateTimeField(blank=True, null=True)),
                ("manager_comments", models.TextField(blank=True)),
                ("hr_approved_at", models.DateTimeField(blank=True, null=True)),
                ("hr_comments", models.TextField(blank=True)),
                ("rejected_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leave_requests",
                        to="hr_portal.employee",
                    ),
                ),
                (
                    "hr_approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hr_approved_leaves",
                        to="hr_portal.employee",
                    ),
                ),
                (
                    "manager_approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="manager_approved_leaves",
                        to="hr_portal.employee",
                    ),
                ),
                (
                    "rejected_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rejected_leaves",
                        to="hr_portal.employee",
                    ),
                ),
                (
                    "leave_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="requests",
                        to="hr_portal.leavetype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Leave Request",
                "verbose_name_plural": "Leave Requests",
                "ordering": ["-created_at"],
                "permissions": [
                    ("approve_leave_as_manager", "Can approve leave as manager"),
                    ("approve_leave_as_hr", "Can approve leave as HR"),
                    ("view_all_leaves", "Can view all leave requests"),
                    ("view_team_leaves", "Can view team leave requests"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("leave_request", "Leave Request"),
                            ("leave_approved", "Leave Approved"),
                            ("leave_rejected", "Leave Rejected"),
                            ("expense_request", "Expense Request"),
                            ("expense_approved", "Expense Approved"),
                            ("expense_rejected", "Expense Rejected"),
                            ("expense_paid", "Expense Paid"),
                            ("timesheet_reminder", "Timesheet Reminder"),
                            ("timesheet_approved", "Timesheet Approved"),
                            ("timesheet_rejected", "Timesheet Rejected"),
                            ("asset_assigned", "Asset Assigned"),
                            ("general", "General"),
                        ],
                        max_length=30,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("message", models.TextField()),
                (
                    "link",
                    models.CharField(
                        blank=True, help_text="URL to related resource", max_length=500
                    ),
                ),
                ("is_read", models.BooleanField(default=False)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hr_notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("project_id", models.CharField(max_length=20, unique=True)),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("client", models.CharField(blank=True, max_length=200)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planning", "Planning"),
                            ("active", "Active"),
                            ("on_hold", "On Hold"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="planning",
                        max_length=20,
                    ),
                ),
                (
                    "budget_hours",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "budget_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("is_billable", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="projects",
                        to="hr_portal.department",
                    ),
                ),
                (
                    "project_manager",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="managed_projects",
                        to="hr_portal.employee",
                    ),
                ),
            ],
            options={
                "verbose_name": "Project",
                "verbose_name_plural": "Projects",
                "ordering": ["-created_at"],
                "permissions": [
                    ("manage_projects", "Can manage projects"),
                    ("view_all_projects", "Can view all projects"),
                ],
            },
        ),
        migrations.CreateModel(
            name="ExpenseRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "request_id",
                    models.CharField(editable=False, max_length=20, unique=True),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("expense_date", models.DateField()),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("USD", "US Dollar"),
                            ("EUR", "Euro"),
                            ("GBP", "British Pound"),
                            ("INR", "Indian Rupee"),
                            ("CAD", "Canadian Dollar"),
                            ("AUD", "Australian Dollar"),
                        ],
                        default="USD",
                        max_length=3,
                    ),
                ),
                (
                    "receipt",
                    models.FileField(
                        blank=True, null=True, upload_to="hr_portal/expense_receipts/"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("manager_approved", "Manager Approved"),
                            ("finance_approved", "Finance Approved"),
                            ("rejected", "Rejected"),
                            ("paid", "Paid"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("manager_approved_at", models.DateTimeField(blank=True, null=True)),
                ("manager_comments", models.TextField(blank=True)),
                ("finance_approved_at", models.DateTimeField(blank=True, null=True)),
                ("finance_comments", models.TextField(blank=True)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("payment_reference", models.CharField(blank=True, max_length=100)),
                ("rejected_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="requests",
                        to="hr_portal.expensecategory",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expense_requests",
                        to="hr_portal.employee",
                    ),
                ),
                (
                    "finance_approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="finance_approved_expenses",
                        to="hr_portal.employee",
                    ),
                ),
                (
                    "manager_approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="manager_approved_expenses",
                        to="hr_portal.employee",
                    ),
                ),
                (
                    "rejected_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rejected_expenses",
                        to="hr_portal.employee",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="expenses",
                        to="hr_portal.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Expense Request",
                "verbose_name_plural": "Expense Requests",
                "ordering": ["-created_at"],
                "permissions": [
                    ("approve_expense_as_manager", "Can approve expense as manager"),
                    ("approve_expense_as_finance", "Can approve expense as finance"),
                    ("mark_expense_paid", "Can mark expense as paid"),
                    ("view_all_expenses", "Can view all expense requests"),
                    ("view_team_expenses", "Can view team expense requests"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Timesheet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("week_start_date", models.DateField(help_text="Monday of the week")),
                ("week_end_date", models.DateField(help_text="Sunday of the week")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "total_hours",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("approval_comments", models.TextField(blank=True)),
                ("rejected_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True)),
                ("is_locked", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_timesheets",
                        to="hr_portal.employee",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timesheets",
                        to="hr_portal.employee",
                    ),
                ),
                (
                    "rejected_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rejected_timesheets",
                        to="hr_portal.employee",
                    ),
                ),
            ],
            options={
                "verbose_name": "Timesheet",
                "verbose_name_plural": "Timesheets",
                "ordering": ["-week_start_date"],
                "permissions": [
                    ("approve_timesheet", "Can approve timesheets"),
                    ("view_all_timesheets", "Can view all timesheets"),
                    ("view_team_timesheets", "Can view team timesheets"),
                ],
                "unique_together": {("employee", "week_start_date")},
            },
        ),
        migrations.CreateModel(
            name="TimesheetEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "hours",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=4,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.25")),
                            django.core.validators.MaxValueValidator(Decimal("24")),
                        ],
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Work description for this entry"
                    ),
                ),
                ("is_billable", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="timesheet_entries",
                        to="hr_portal.project",
                    ),
                ),
                (
                    "timesheet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="hr_portal.timesheet",
                    ),
                ),
            ],
            options={
                "verbose_name": "Timesheet Entry",
                "verbose_name_plural": "Timesheet Entries",
                "ordering": ["date", "project"],
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "Created"),
                            ("update", "Updated"),
                            ("delete", "Deleted"),
                            ("submit", "Submitted"),
                            ("approve", "Approved"),
                            ("reject", "Rejected"),
                            ("cancel", "Cancelled"),
                            ("assign", "Assigned"),
                            ("return", "Returned"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(
                        choices=[
                            ("employee", "Employee"),
                            ("leave_request", "Leave Request"),
                            ("expense_request", "Expense Request"),
                            ("timesheet", "Timesheet"),
                            ("asset", "Asset"),
                            ("project", "Project"),
                        ],
                        max_length=30,
                    ),
                ),
                ("entity_id", models.CharField(max_length=50)),
                ("entity_description", models.CharField(blank=True, max_length=200)),
                ("performed_at", models.DateTimeField(auto_now_add=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("old_values", models.JSONField(blank=True, default=dict)),
                ("new_values", models.JSONField(blank=True, default=dict)),
                ("comments", models.TextField(blank=True)),
                (
                    "performed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hr_audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit Log",
                "verbose_name_plural": "Audit Logs",
                "ordering": ["-performed_at"],
                "indexes": [
                    models.Index(
                        fields=["entity_type", "entity_id"],
                        name="hr_portal_a_entity__77e0e1_idx",
                    ),
                    models.Index(
                        fields=["performed_by", "performed_at"],
                        name="hr_portal_a_perform_9f5dcf_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="HolidayCalendar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("date", models.DateField()),
                (
                    "holiday_type",
                    models.CharField(
                        choices=[
                            ("public", "Public Holiday"),
                            ("company", "Company Holiday"),
                            ("optional", "Optional Holiday"),
                            ("restricted", "Restricted Holiday"),
                        ],
                        default="public",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        help_text="Leave blank for company-wide",
                        max_length=100,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("year", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Holiday",
                "verbose_name_plural": "Holidays",
                "ordering": ["date"],
                "unique_together": {("name", "date", "location")},
            },
        ),
        migrations.CreateModel(
            name="LeaveBalance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.PositiveIntegerField()),
                (
                    "allocated_days",
                    models.DecimalField(decimal_places=1, default=0, max_digits=5),
                ),
                (
                    "used_days",
                    models.DecimalField(decimal_places=1, default=0, max_digits=5),
                ),
                (
                    "carried_forward_days",
                    models.DecimalField(decimal_places=1, default=0, max_digits=5),
                ),
                (
                    "adjusted_days",
                    models.DecimalField(
                        decimal_places=1,
                        default=0,
                        help_text="Manual adjustments",
                        max_digits=5,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leave_balances",
                        to="hr_portal.employee",
                    ),
                ),
                (
                    "leave_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="balances",
                        to="hr_portal.leavetype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Leave Balance",
                "verbose_name_plural": "Leave Balances",
                "ordering": ["employee", "leave_type"],
                "unique_together": {("employee", "leave_type", "year")},
            },
        ),
        migrations.CreateModel(
            name="ProjectAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("member", "Team Member"),
                            ("lead", "Team Lead"),
                            ("manager", "Project Manager"),
                            ("consultant", "Consultant"),
                        ],
                        default="member",
                        max_length=20,
                    ),
                ),
                (
                    "allocation_percentage",
                    models.PositiveIntegerField(
                        default=100,
                        help_text="Percentage of time allocated to this project",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_assignments",
                        to="hr_portal.employee",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="hr_portal.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Project Assignment",
                "verbose_name_plural": "Project Assignments",
                "ordering": ["project", "employee"],
                "unique_together": {("project", "employee")},
            },
        ),
    ]
